In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4])

In [3]:
array

array([1, 2, 3, 4])

In [4]:
array_of_zeros = np.zeros((3,4))

In [5]:
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
array_empty = np.empty((2,3))

In [7]:
array_empty

array([[3.56011818e-307, 2.33644129e-307, 4.00540117e-307],
       [2.11395937e-307, 2.33647015e-307, 1.05695422e-307]])

In [14]:
array_eye = np.eye((2))

In [15]:
array_eye

array([[1., 0.],
       [0., 1.]])

In [16]:
array_of_evens = np.arange(2,20,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
array_of_odds = np.arange(3,20,2)

In [19]:
array_of_odds

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [20]:
# how to create 2D array

array_2D = np.array([(1,2,3),(4,5,6)])
array_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
array_2D.shape

(2, 3)